// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=tracks
//

// Package tracks is a generated GoMock package.
package tracks

import (
	context "context"
	reflect "reflect"

	spotify "github.com/rdy24/spotify-catalog/internal/repository/spotify"
	gomock "go.uber.org/mock/gomock"
)

// MockSpotifyOutbound is a mock of SpotifyOutbound interface.
type MockSpotifyOutbound struct {
	ctrl     *gomock.Controller
	recorder *MockSpotifyOutboundMockRecorder
	isgomock struct{}
}

// MockSpotifyOutboundMockRecorder is the mock recorder for MockSpotifyOutbound.
type MockSpotifyOutboundMockRecorder struct {
	mock *MockSpotifyOutbound
}

// NewMockSpotifyOutbound creates a new mock instance.
func NewMockSpotifyOutbound(ctrl *gomock.Controller) *MockSpotifyOutbound {
	mock := &MockSpotifyOutbound{ctrl: ctrl}
	mock.recorder = &MockSpotifyOutboundMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotifyOutbound) EXPECT() *MockSpotifyOutboundMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSpotifyOutbound) Search(ctx context.Context, query string, limit, offset int) (*spotify.SpotifySearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit, offset)
	ret0, _ := ret[0].(*spotify.SpotifySearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSpotifyOutboundMockRecorder) Search(ctx, query, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSpotifyOutbound)(nil).Search), ctx, query, limit, offset)
}
